<?php
$_config['debug']=false;
$_config['mssql']=[
	"ip"=>"192.168.1.78",
	"id"=>"sror_server",
	"pw"=>"169841",
	"db"=>"SILKROAD_R_ACCOUNT",
	"db2"=>"SILKROAD_R_ACCOUNT", //<--GB_JoymaxPortal
	"vip"=>"TB_VIP_Info" //<--MU_VIP_Info
];
$_config['site_info']=[
	"ssl"=>false,
	"domain"=>"webmall.cfxdb.com",
	"title"=>"Silkroad Online",
	"description"=>"The most updated Silkroad server with the newest files available is ready to bring this game to the next level. The future is finally here!",
	"keyword"=>"silkroad, silkroadonline, joymax, onlinesilkroad, silkroad-online",
	"secret"=>"joymax.com",
	"extension"=>".asp",
	"vkey"=>"eset5ag.nsy-g6ky5.mp",
	"servername"=>"TEST",
	"chargeurl"=>"http://yourdomain.com/reloadsilk.asp",
	"viptiername"=>[
		//you can use whatever names you want
		0=>"Normal",
		1=>"BRONZE", //<--VIPLv = 1
		2=>"SILVER",
		3=>"GOLD",
		4=>"PLATINUM",
		5=>"SPECIAL",
		6=>"GM's BFF"
	]
];
$_config['pages']=[
	'itembuygame',
	'gateway',
	'error'
];
$_config['message']=[
	//its all english in default, only us,eg,tr,es,de language is accepted atm.
	"us"=>[
		"Item Mall",
		"Premium Mall",
		"Silk Mall",
		"Reserverd",[
			"Item Name",
			"Server",
			"Qty",
			"Price",
			"Purchase",
			"Delete",
			"Delete All",
			"Purchase Selected",
			"Purchase All",
			"No Data"
		],
		"History",[
			"Year",
			"Month",
			"Total silks spent",
			"Total Purchase in Premium Mall (a)",
			"Total Purchase in Silk Mall (b)",
			"Total Purchase of Silks (a)+(b)",
			"* Silk received as gifts are spent first when purchasing items in game.",
			"But Item History",
			"Date",
			"Item",
			"Server",
			"Price",
			"Complete Receiving Item(s) In-Game",
			"No history available"
		],
		"Buy Item",[
			"Item Name",
			"ID",
			"Server",
			"Qty",
			"Price",
			"Available Balance",
			"Click the [Silk Charge] button on the top right corner to buy more credits.",
			"Item Successfully Purchased",
			"1) Start the game and enter the server you chose when you bought the item.",
			"2) Enter the game with the character that will receive the item.",
			"3) If you right-click on the icon above in the game, the purchased item list will appear. When you click [get] from the list, the selected item will be moved to the inventory.",
			"Please view purchase information.",
			"Limited-time items can only be used until their expiration date. Check the date.",
			"Interner error occur while purchasing",
			"Report this to the administrator asap.",
			"* The item will be given to the character on the selected server. Please be careful in selecting the server.",
			"Purchase",
			"Confirm",
			"Cancel",
			"Back",
			"History"
		],
		"New & Best",
		"Search",
		"Purchase",
		"Buy Item Guide",
		"Search Result"
	],
	"es"=>[
		"Item Mall",
		"Premium Mall",
		"Silk Mall",
		"Reserverd",[
			"Item Name",
			"Server",
			"Qty",
			"Price",
			"Purchase",
			"Delete",
			"Delete All",
			"Purchase Selected",
			"Purchase All",
			"No Data"
		],
		"History",[
			"Year",
			"Month",
			"Total silks spent",
			"Total Purchase in Premium Mall (a)",
			"Total Purchase in Silk Mall (b)",
			"Total Purchase of Silks (a)+(b)",
			"* Silk received as gifts are spent first when purchasing items in game.",
			"But Item History",
			"Date",
			"Item",
			"Server",
			"Price",
			"Complete Receiving Item(s) In-Game",
			"No history available"
		],
		"Buy Item",[
			"Item Name",
			"ID",
			"Server",
			"Qty",
			"Price",
			"Available Balance",
			"Click the [Silk Charge] button on the top right corner to buy more credits.",
			"Item Successfully Purchased",
			"1) Start the game and enter the server you chose when you bought the item.",
			"2) Enter the game with the character that will receive the item.",
			"3) If you right-click on the icon above in the game, the purchased item list will appear. When you click [get] from the list, the selected item will be moved to the inventory.",
			"Please view purchase information.",
			"Limited-time items can only be used until their expiration date. Check the date.",
			"Interner error occur while purchasing",
			"Report this to the administrator asap.",
			"* The item will be given to the character on the selected server. Please be careful in selecting the server.",
			"Purchase",
			"Confirm",
			"Cancel",
			"Back",
			"History"
		],
		"New & Best",
		"Search",
		"Purchase",
		"Buy Item Guide",
		"Search Result"
	],
	"de"=>[
		"Item Mall",
		"Premium Mall",
		"Silk Mall",
		"Reserverd",[
			"Item Name",
			"Server",
			"Qty",
			"Price",
			"Purchase",
			"Delete",
			"Delete All",
			"Purchase Selected",
			"Purchase All",
			"No Data"
		],
		"History",[
			"Year",
			"Month",
			"Total silks spent",
			"Total Purchase in Premium Mall (a)",
			"Total Purchase in Silk Mall (b)",
			"Total Purchase of Silks (a)+(b)",
			"* Silk received as gifts are spent first when purchasing items in game.",
			"But Item History",
			"Date",
			"Item",
			"Server",
			"Price",
			"Complete Receiving Item(s) In-Game",
			"No history available"
		],
		"Buy Item",[
			"Item Name",
			"ID",
			"Server",
			"Qty",
			"Price",
			"Available Balance",
			"Click the [Silk Charge] button on the top right corner to buy more credits.",
			"Item Successfully Purchased",
			"1) Start the game and enter the server you chose when you bought the item.",
			"2) Enter the game with the character that will receive the item.",
			"3) If you right-click on the icon above in the game, the purchased item list will appear. When you click [get] from the list, the selected item will be moved to the inventory.",
			"Please view purchase information.",
			"Limited-time items can only be used until their expiration date. Check the date.",
			"Interner error occur while purchasing",
			"Report this to the administrator asap.",
			"* The item will be given to the character on the selected server. Please be careful in selecting the server.",
			"Purchase",
			"Confirm",
			"Cancel",
			"Back",
			"History"
		],
		"New & Best",
		"Search",
		"Purchase",
		"Buy Item Guide",
		"Search Result"
	],
	"tr"=>[
		"Item Mall",
		"Premium Mall",
		"Silk Mall",
		"Reserverd",[
			"Item Name",
			"Server",
			"Qty",
			"Price",
			"Purchase",
			"Delete",
			"Delete All",
			"Purchase Selected",
			"Purchase All",
			"No Data"
		],
		"History",[
			"Year",
			"Month",
			"Total silks spent",
			"Total Purchase in Premium Mall (a)",
			"Total Purchase in Silk Mall (b)",
			"Total Purchase of Silks (a)+(b)",
			"* Silk received as gifts are spent first when purchasing items in game.",
			"But Item History",
			"Date",
			"Item",
			"Server",
			"Price",
			"Complete Receiving Item(s) In-Game",
			"No history available"
		],
		"Buy Item",[
			"Item Name",
			"ID",
			"Server",
			"Qty",
			"Price",
			"Available Balance",
			"Click the [Silk Charge] button on the top right corner to buy more credits.",
			"Item Successfully Purchased",
			"1) Start the game and enter the server you chose when you bought the item.",
			"2) Enter the game with the character that will receive the item.",
			"3) If you right-click on the icon above in the game, the purchased item list will appear. When you click [get] from the list, the selected item will be moved to the inventory.",
			"Please view purchase information.",
			"Limited-time items can only be used until their expiration date. Check the date.",
			"Interner error occur while purchasing",
			"Report this to the administrator asap.",
			"* The item will be given to the character on the selected server. Please be careful in selecting the server.",
			"Purchase",
			"Confirm",
			"Cancel",
			"Back",
			"History"
		],
		"New & Best",
		"Search",
		"Purchase",
		"Buy Item Guide",
		"Search Result"
	],
	"eg"=>[
		"Item Mall",
		"Premium Mall",
		"Silk Mall",
		"Reserverd",[
			"Item Name",
			"Server",
			"Qty",
			"Price",
			"Purchase",
			"Delete",
			"Delete All",
			"Purchase Selected",
			"Purchase All",
			"No Data"
		],
		"History",[
			"Year",
			"Month",
			"Total silks spent",
			"Total Purchase in Premium Mall (a)",
			"Total Purchase in Silk Mall (b)",
			"Total Purchase of Silks (a)+(b)",
			"* Silk received as gifts are spent first when purchasing items in game.",
			"But Item History",
			"Date",
			"Item",
			"Server",
			"Price",
			"Complete Receiving Item(s) In-Game",
			"No history available"
		],
		"Buy Item",[
			"Item Name",
			"ID",
			"Server",
			"Qty",
			"Price",
			"Available Balance",
			"Click the [Silk Charge] button on the top right corner to buy more credits.",
			"Item Successfully Purchased",
			"1) Start the game and enter the server you chose when you bought the item.",
			"2) Enter the game with the character that will receive the item.",
			"3) If you right-click on the icon above in the game, the purchased item list will appear. When you click [get] from the list, the selected item will be moved to the inventory.",
			"Please view purchase information.",
			"Limited-time items can only be used until their expiration date. Check the date.",
			"Interner error occur while purchasing",
			"Report this to the administrator asap.",
			"* The item will be given to the character on the selected server. Please be careful in selecting the server.",
			"Purchase",
			"Confirm",
			"Cancel",
			"Back",
			"History"
		],
		"New & Best",
		"Search",
		"Purchase",
		"Buy Item Guide",
		"Search Result"
	]
];